import type { CompanyProfile } from './companyProfile'

export type GeneratedDocument = {
  key: string
  title: string
  description: string
  fileName: string
  content: string
}

function lines(parts: string[]) {
  return parts.join('\n')
}

export function buildDocuments(profile: CompanyProfile): GeneratedDocument[] {
  return [
    {
      key: 'company-brief',
      title: 'Ficha executiva da empresa',
      description: 'Resumo societario, comercial e operacional para alinhamento interno e parceiros.',
      fileName: 'prescripta-ficha-executiva.md',
      content: lines([
        `# Ficha Executiva - ${profile.brandName}`,
        '',
        '## Identificacao',
        `- Razao social: ${profile.legalEntityName}`,
        `- Marca: ${profile.brandName}`,
        `- Estrutura societaria: ${profile.legalStructure}`,
        `- Sede: ${profile.headquarters}`,
        `- Ano ou marco de fundacao: ${profile.foundingDate}`,
        `- Website: ${profile.website}`,
        '',
        '## Estrutura operacional',
        `- Estagio atual: ${profile.companyStage}`,
        `- Fundadores ou socios-chave: ${profile.founderNames}`,
        `- Lider comercial: ${profile.commercialLead}`,
        `- Responsavel juridico: ${profile.legalLead}`,
        `- Contato de privacidade / DPO: ${profile.dpoContact}`,
        `- Contato de suporte: ${profile.supportContact}`,
        '',
        '## Tese comercial',
        `- Oferta central: ${profile.coreOffer}`,
        `- Modelo comercial: ${profile.commercialModel}`,
        `- Motion de vendas: ${profile.salesMotion}`,
        `- ICP principal: ${profile.primaryIcp}`,
        `- ICP secundario: ${profile.secondaryIcp}`,
        '',
        '## Politica comercial atual',
        `- Plano de entrada: ${profile.startPlanPrice}`,
        `- Plano clinica: ${profile.clinicPlanPrice}`,
        `- Politica de setup: ${profile.setupPolicy}`,
        `- Politica de piloto: ${profile.pilotPolicy}`,
        '',
        '## Roadmap critico',
        `- Nota regulatoria: ${profile.roadmapNote}`,
      ]),
    },
    {
      key: 'commercial-proposal',
      title: 'Modelo de proposta comercial',
      description: 'Versao base exportavel para personalizacao por cliente.',
      fileName: 'prescripta-proposta-comercial.md',
      content: lines([
        `# Proposta Comercial - ${profile.brandName}`,
        '',
        '## 1. Contexto',
        `${profile.brandName} atua como ${profile.coreOffer}. A empresa opera em modelo ${profile.commercialModel}, com foco inicial em ${profile.primaryIcp}.`,
        '',
        '## 2. Escopo da contratacao',
        `O servico contempla licenciamento da plataforma ${profile.brandName}, configuracao operacional inicial, treinamento e suporte conforme o plano contratado. A plataforma organiza prazo, retorno, renovacao e confirmacao de forma observavel, preservando a autoridade final do prescritor.`,
        '',
        '## 3. Limites da oferta',
        `${profile.brandName} nao substitui decisao clinica, nao atua como prontuario generico e nao promete cobertura regulatoria fora do escopo expressamente contratado.`,
        '',
        '## 4. Modelo comercial',
        `- Motion de venda: ${profile.salesMotion}`,
        `- Plano de entrada de referencia: ${profile.startPlanPrice}`,
        `- Plano clinica de referencia: ${profile.clinicPlanPrice}`,
        `- Politica de setup: ${profile.setupPolicy}`,
        '',
        '## 5. Implantacao',
        `A implantacao segue kickoff, mapeamento de fluxo atual, configuracao, treinamento por papel e go-live assistido. A politica atual de pilotos e validacoes e: ${profile.pilotPolicy}`,
        '',
        '## 6. Base juridica e confianca',
        `A relacao contratual sera acompanhada por contrato SaaS, DPA, politica de privacidade, politica de IA e materiais de trust center. O contato base para privacidade e ${profile.dpoContact}.`,
        '',
        '## 7. Proximos passos',
        '- Validar escopo, usuarios e rotina-alvo.',
        '- Confirmar plano, setup e cronograma.',
        '- Alinhar juridico-operacional.',
        '- Assinar proposta e agendar kickoff.',
      ]),
    },
    {
      key: 'pilot-term',
      title: 'Termo-base de piloto pago',
      description: 'Documento para design partners e pilotos de validacao estruturada.',
      fileName: 'prescripta-termo-piloto.md',
      content: lines([
        `# Termo-Base de Piloto - ${profile.brandName}`,
        '',
        '## Objeto',
        `${profile.brandName} disponibilizara sua plataforma em formato de piloto controlado para validar aderencia operacional, ativacao da equipe e valor percebido no fluxo de recorrencia prescricional.`,
        '',
        '## Premissa de estagio',
        `O estagio atual da empresa e: ${profile.companyStage}. Por isso, o piloto existe para validar uso real e nao para manter acesso gratuito indefinido.`,
        '',
        '## Politica do piloto',
        `${profile.pilotPolicy}`,
        '',
        '## Entregaveis da Prescripta',
        '- Kickoff comercial-operacional.',
        '- Configuracao inicial da rotina contratada.',
        '- Treinamento dos usuarios criticos.',
        '- Suporte assistido durante o periodo do piloto.',
        '',
        '## Responsabilidades do cliente',
        '- Nomear owner operacional.',
        '- Disponibilizar usuarios e fluxo-alvo para configuracao.',
        '- Participar das revisoes de ativacao e decisao final.',
        '',
        '## Encerramento',
        'Ao final do periodo, as partes registrarao uma revisao de resultados e decidirao pela conversao em contrato recorrente, extensao formal mediante novo acordo ou encerramento do piloto.',
      ]),
    },
    {
      key: 'dpa-summary',
      title: 'Anexo comercial de privacidade e DPA',
      description: 'Resumo operacional para mandar junto da proposta antes da minuta final.',
      fileName: 'prescripta-anexo-dpa-comercial.md',
      content: lines([
        `# Anexo Comercial de Privacidade - ${profile.brandName}`,
        '',
        '## Papel da Prescripta',
        `${profile.brandName} atua como fornecedora SaaS em saude e, nas atividades de tratamento executadas em nome do cliente dentro do fluxo contratado, tende a operar como operadora de dados pessoais. Em atividades proprias de marketing, faturamento, governanca contratual e seguranca, pode atuar como controladora conforme a finalidade aplicavel.`,
        '',
        '## Governanca minima',
        `- Responsavel juridico: ${profile.legalLead}`,
        `- Contato de privacidade / DPO: ${profile.dpoContact}`,
        `- Contato de suporte: ${profile.supportContact}`,
        '',
        '## Compromissos-base',
        '- Seguir instrucoes documentadas do cliente quando atuar em seu contexto operacional.',
        '- Adotar medidas tecnicas e organizacionais compativeis com o risco e o estagio da operacao.',
        '- Manter trilha de governanca contratual, politica de privacidade, politica de IA e lista de subprocessadores.',
        '- Comunicar incidentes conforme procedimento contratual e requisitos legais aplicaveis.',
        '',
        '## Limites e observacoes',
        `${profile.roadmapNote}`,
      ]),
    },
  ]
}
